use_frameworks!

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

target 'Content_Example' do
  pod 'Content', :path => '../'
  pod 'AlamofireImage', '~> 3.0'
#  pod 'Eureka', git: 'https://github.com/mojidabckuu/Eureka'

  target 'Content_Tests' do
  end
end
